### ISSUE TITLE
Handling exceptions in DataflowJobManager

### ISSUE THREAD

**Issue by igitur** [ptsteward/ConcurrentFlows#1]
Hi Josh,

I hope you're OK with taking questions here. Else, let me know and I'll rather submit it on StackOverflow. I've recently discovered your archived blog and this repo. It's awesome thanks. I want to use `DataflowJobManager` to throttle incoming requests that should consume a potentially slow operation. The `DataflowJobManager` works perfectly, exception with the operation throws an exception.

I've read the [Microsoft blog](https://devblogs.microsoft.com/pfxteam/exception-handling-in-tpl-dataflow-networks/) on how to handle exceptions, but I can't figure out how to apply that to the `DataflowJobManager`.

Here is a code sample to illustrate the issue:
```c#
private static async Task Main(string[] args)
{
    var transformBlock = new TransformBlock<KeyValuePair<Guid, double>, KeyValuePair<Guid, double>>(input =>
        {
            if (input.Value <= 0)
            {
                Console.WriteLine("Only positive values allowed");
                throw new ArgumentOutOfRangeException(nameof(input), "Only positive values allowed");
            }

            return new KeyValuePair<Guid, double>(input.Key, Math.Log10(input.Value));
        });

    var manager = new DataflowJobManager<double, double>(transformBlock);

    var rnd = new Random(100);

    for (var i = 0; i < 20; i++)
    {
        var input = rnd.Next(-1, 10);
        var output = await manager.SubmitRequest(input);
        Console.WriteLine($"Log({input}) = {output}");
    }

    Console.WriteLine("Press any key to quit...");
    Console.ReadKey(false);
}
```

When the exception is thrown in the `transformBlock`, the whole queue freezes. As I say, if I should rather post this on StackOverflow, please let me know. Thanks

**Comment by igitur** [comment]
Oh, the code above works only if https://github.com/ptsteward/ConcurrentFlows/blob/0e173d3a28c6c6d0a48cd09946238e9f2164a9a5/ConcurrentFlows.DataflowJobs/DataflowJobManager.cs#L17 is replaced with `this.JobHandler = jobHandler;`. I can log a PR for that if you're taking pull requests.

**Comment by ptsteward** [comment]
Thank for spotting that! I just edited the master branch.

**Comment by igitur** [comment]
Thanks for the fix, but do you have any comment on my actual original question on how to handle exceptions? Thanks

**Comment by ptsteward** [comment]
Well, the thing with exceptions in dataflow is that they kill the whole block. If you're propagating completion they kill the pipeline. So you want to handle exceptions within the block itself. If you want to safely pass errors throughout your pipeline without faulting a block then use some sort of mechanism to transmit that information without re-throwing the exception: tuples, an error property etc.

**Comment by igitur** [comment]
Oh of course. As simple as that. I think that Microsoft blog was a bit of a red herring then. 

Why did you abandon the blog, if I may ask?
